[package]
name = "hellwrld"
version = "0.1.0"
authors = ["VdanielVPL"]
edition = "2021"

[profile.release]
opt-level = "s"
debug-assertions = false
panic = "abort"
codegen-units = 1
strip = true
lto = "fat"
debug = false